bubblesort: bubblesort.o
	gcc -m32 -Wall -g -o bubblesort bubblesort.o

bubblesort.o : lab3_bubblesort.c
	gcc -m32 -Wall -g -c -o bubblesort.o lab3_bubblesort.c


.PHONY: clean

clean:
	rm -f *.o bubblesort